version: "3.7"
services:
  superset:
    image: apache/superset:latest
    container_name: superset
    restart: always
    environment:
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_SECRET_KEY: "RVhFXmZrQlZjQlFkbEtCa1RHT3FkR25YZExWd1Z3dm1FVHRJQm9Zb2REeg=="
      SUPERSET_ADMIN_USERNAME: "admin"
      SUPERSET_ADMIN_PASSWORD: "admin"
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://mysql:admin@mysql:3306/warehouse # Connect to MySQL from database.yml
    ports:
      - "8088:8088"
    depends_on:
      - redis
    volumes:
      - superset_home:/app/superset_home
      - superset_logs:/app/superset_logs
    networks:
      - bigdata

volumes:
  superset_home:
  superset_logs:

networks:
  bigdata:
    external: true
